classDiagram
    class Estudiante {
        -id: int
        -nombre: string
        -email: string
        -carrera: string
        +registrar(): void
        +editarPerfil(): void
        +consultarCursosDisponibles(): List<Curso>
        +consultarCursosMatriculados(): List<Curso>
    }
 
    class Curso {
        -codigo: string
        -nombre: string
        -creditos: int
        +matricular(): void
        +retirar(): void
    }

    class Periodo {
        -año: int
        -nombre: string
        -activo: boolean
        +iniciarPeriodo(): void
        +finalizarPeriodo(): void

    }


    class Profesor {
        -idCurso: string 
        -idPeriodo: int
        -idProfesor: int
        -horario: string
        +asignarProfesor(): void
        +definirHorario(): void

    }

    class Matricula {
        -idMatricula
        -idEstudiante 
        -idGrupo
        -fecha: date

  }


    class Grupo {
        -idgrupo: int
        -idCurso: int 
        -idProfesor: int?
        -idPeriodo: int
        -capacidad: int
        -numero_grupo: int
        -horario: string
        +agregarEstudiante(): void
        +consultarEstudiante(): List<Estudiante>

  }

    Grupo "1" -- "1" Curso : ofrece
    Grupo "1" -- "1" Profesor : impartido por
    Grupo "1" -- "1" Periodo : en
    Estudiante "1" --> "*" Matricula : realiza
    Matricula "1" -- "1" Grupo : de
